Выполнена домашняя работа 4
exen01/CSharpEducation pull request #1
Opened 2024-09-20 10:35 UTC by exen01

2024-09-20 11:19 UTC, Dezodemius requested changes

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/Employee.cs
> +/// Базовый класс представляющий сотрудника.
Не нужно писать, что это класс. Это видно из сигнатуры. Для методов, интерфейсов и тд это тоже актуально

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/Employee.cs
> +  /// <summary>
Нужно добавить регионы из соглашению по кодированию

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/Employee.cs
> +  protected Employee(string name, decimal baseSalary)
Конструктор нужно унести вниз файла

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/Employee.cs
> +  /// Возвращает текстовое представление сотрудника.
доку можно не писать. Она из базового класса придёт

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/EmployeeManager.cs
> +/// <typeparam name="T">Тип сотрудника</typeparam>
точка в конце нужна

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/EmployeeManager.cs
> +    Console.WriteLine(_employees.TryAdd(employee.Name, employee)
не нужно в этом классе писать в консоль. Это лучше вынести в Program. Если не удалось добавить, то выбрасывать исключение

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/EmployeeManager.cs
> +  /// <param name="employee"></param>
Нужно дописать доку для аргумента

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/FullTimeEmployee.cs
> +  public FullTimeEmployee(string name, decimal baseSalary) : base(name, baseSalary)
Вниз класса

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/IEmployeeManager.cs
> +  void Add(T employee);
Дока нужна. И разделить члены пустой строкой

2024-09-20 11:19 UTC, Dezodemius commented on EmployeeAccountingSystem/IEmployeeManager.cs
> +  void Add(T employee);
Соответственно, в реализациях интерфейса не нужно писать доку. Она возьмётся из интерфейса

2024-09-20 16:38 UTC, exen01 commented
Добавил исправления

2024-09-21 12:15 UTC, Dezodemius approved these changes

2024-09-21 12:26 UTC, merged