Выполнена домашняя работа 5
exen01/CSharpEducation pull request #2
Opened 2024-09-20 10:44 UTC by exen01

2024-09-20 11:19 UTC, Dezodemius requested changes

2024-09-20 11:19 UTC, Dezodemius commented on UserAccountingSystem/User.cs
> +public class User
Не нужно писать слово класс в доке

2024-09-20 11:19 UTC, Dezodemius commented on UserAccountingSystem/User.cs
> +  public User(int id, string name, string email)
Нужно в класс добавить регионы

2024-09-20 16:39 UTC, exen01 commented
Добавил исправления

2024-09-21 12:16 UTC, Dezodemius approved these changes

2024-09-21 12:28 UTC, Dezodemius approved these changes

2024-09-21 12:37 UTC, merged